# Generated by Django 4.1.5 on 2023-04-22 16:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                ("CartID", models.AutoField(primary_key=True, serialize=False)),
                ("Quantity", models.PositiveIntegerField()),
                ("Price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("DateAdded", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "MedicineID",
                    models.ForeignKey(
                        db_column="MedicineID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="myapp.medicines",
                    ),
                ),
                (
                    "PatientID",
                    models.ForeignKey(
                        db_column="PatientID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="myapp.patients",
                    ),
                ),
            ],
        ),
    ]
