# Generated by Django 4.1.5 on 2023-04-23 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_cart"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cart",
            options={"managed": False},
        ),
    ]
