# Generated by Django 4.1.5 on 2023-04-23 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_alter_cart_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cart",
            options={},
        ),
    ]
