# Generated by Django 4.1.5 on 2023-04-23 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_alter_cart_options"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="cart",
            table="cart",
        ),
    ]
