# Generated by Django 4.1.5 on 2023-03-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "appointmentid",
                    models.IntegerField(
                        db_column="AppointmentID", primary_key=True, serialize=False
                    ),
                ),
                ("date", models.DateField(blank=True, db_column="Date", null=True)),
                ("time", models.TimeField(blank=True, db_column="Time", null=True)),
                (
                    "reason",
                    models.CharField(
                        blank=True, db_column="Reason", max_length=255, null=True
                    ),
                ),
            ],
            options={
                "db_table": "appointment",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
            ],
            options={
                "db_table": "auth_group",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthGroupPermissions",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "auth_group_permissions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("codename", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "auth_permission",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("is_superuser", models.IntegerField()),
                ("username", models.CharField(max_length=150, unique=True)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("email", models.CharField(max_length=254)),
                ("is_staff", models.IntegerField()),
                ("is_active", models.IntegerField()),
                ("date_joined", models.DateTimeField()),
            ],
            options={
                "db_table": "auth_user",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUserGroups",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "auth_user_groups",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUserUserPermissions",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "auth_user_user_permissions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Branches",
            fields=[
                (
                    "branchid",
                    models.IntegerField(
                        db_column="BranchID", primary_key=True, serialize=False
                    ),
                ),
                ("street_number", models.CharField(max_length=255)),
                ("street_name", models.CharField(max_length=255)),
                ("apt_number", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(max_length=255)),
                ("zipcode", models.CharField(db_column="zipCode", max_length=255)),
                ("state", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=255)),
                (
                    "contactnumber",
                    models.BigIntegerField(
                        blank=True, db_column="ContactNumber", null=True
                    ),
                ),
                ("email", models.CharField(db_column="Email", max_length=255)),
            ],
            options={
                "db_table": "branches",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoAdminLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_time", models.DateTimeField()),
                ("object_id", models.TextField(blank=True, null=True)),
                ("object_repr", models.CharField(max_length=200)),
                ("action_flag", models.PositiveSmallIntegerField()),
                ("change_message", models.TextField()),
            ],
            options={
                "db_table": "django_admin_log",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoContentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_label", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "django_content_type",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoMigrations",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("app", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("applied", models.DateTimeField()),
            ],
            options={
                "db_table": "django_migrations",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoSession",
            fields=[
                (
                    "session_key",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("session_data", models.TextField()),
                ("expire_date", models.DateTimeField()),
            ],
            options={
                "db_table": "django_session",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Doctors",
            fields=[
                (
                    "doctorid",
                    models.IntegerField(
                        db_column="DoctorID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "doctor_name_fname",
                    models.CharField(db_column="Doctor_Name_Fname", max_length=50),
                ),
                (
                    "doctor_name_mname",
                    models.CharField(
                        blank=True,
                        db_column="Doctor_Name_Mname",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "doctor_name_lname",
                    models.CharField(db_column="Doctor_Name_Lname", max_length=50),
                ),
                (
                    "specialisation_description",
                    models.CharField(
                        db_column="Specialisation_Description", max_length=100
                    ),
                ),
                (
                    "contactnumber_type",
                    models.CharField(db_column="ContactNumber_type", max_length=20),
                ),
                (
                    "contactnumber_number",
                    models.IntegerField(db_column="ContactNumber_number", unique=True),
                ),
                ("email_type", models.CharField(db_column="Email_type", max_length=10)),
                (
                    "email_address",
                    models.CharField(
                        db_column="Email_address", max_length=100, unique=True
                    ),
                ),
            ],
            options={
                "db_table": "doctors",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Medicalhistory",
            fields=[
                (
                    "medicalhistid",
                    models.IntegerField(
                        db_column="MedicalHistID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, db_column="Description", max_length=255, null=True
                    ),
                ),
            ],
            options={
                "db_table": "medicalhistory",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Medicines",
            fields=[
                (
                    "medicineid",
                    models.IntegerField(
                        db_column="MedicineID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(db_column="Name", max_length=50, unique=True),
                ),
                (
                    "composition",
                    models.CharField(db_column="Composition", max_length=50),
                ),
                ("ingredient", models.CharField(db_column="Ingredient", max_length=50)),
                ("type", models.CharField(db_column="Type", max_length=20)),
                (
                    "price",
                    models.DecimalField(
                        db_column="Price", decimal_places=2, max_digits=10
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        db_column="Cost", decimal_places=2, max_digits=10
                    ),
                ),
                ("currency", models.CharField(db_column="Currency", max_length=10)),
            ],
            options={
                "db_table": "medicines",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MedSupp",
            fields=[
                (
                    "msid",
                    models.IntegerField(
                        db_column="MSID", primary_key=True, serialize=False
                    ),
                ),
            ],
            options={
                "db_table": "med_supp",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "orderid",
                    models.IntegerField(
                        db_column="OrderID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(blank=True, db_column="Quantity", null=True),
                ),
                ("date", models.DateField(blank=True, db_column="Date", null=True)),
                (
                    "deliverystatus",
                    models.CharField(
                        blank=True,
                        db_column="DeliveryStatus",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "orders",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Patients",
            fields=[
                (
                    "patientid",
                    models.IntegerField(
                        db_column="PatientID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "name_fname",
                    models.CharField(
                        blank=True, db_column="Name_Fname", max_length=50, null=True
                    ),
                ),
                (
                    "name_mname",
                    models.CharField(
                        blank=True, db_column="Name_Mname", max_length=50, null=True
                    ),
                ),
                (
                    "name_lname",
                    models.CharField(
                        blank=True, db_column="Name_Lname", max_length=50, null=True
                    ),
                ),
                (
                    "address_street_number",
                    models.CharField(
                        blank=True,
                        db_column="Address_street_number",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "address_street_name",
                    models.CharField(
                        blank=True,
                        db_column="Address_street_name",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "address_apt_number",
                    models.CharField(
                        blank=True,
                        db_column="Address_apt_number",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "address_city",
                    models.CharField(
                        blank=True, db_column="Address_city", max_length=50, null=True
                    ),
                ),
                (
                    "address_zipcode",
                    models.IntegerField(
                        blank=True, db_column="Address_zipCode", null=True
                    ),
                ),
                (
                    "address_state",
                    models.CharField(
                        blank=True, db_column="Address_state", max_length=50, null=True
                    ),
                ),
                (
                    "address_country",
                    models.CharField(
                        blank=True,
                        db_column="Address_country",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("dob", models.DateField(blank=True, db_column="DOB", null=True)),
                (
                    "contactnumber_type",
                    models.CharField(
                        blank=True,
                        db_column="ContactNumber_type",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "contactnumber_number",
                    models.IntegerField(
                        blank=True, db_column="ContactNumber_number", null=True
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True, db_column="Gender", max_length=1, null=True
                    ),
                ),
                (
                    "email_type",
                    models.CharField(
                        blank=True, db_column="Email_type", max_length=50, null=True
                    ),
                ),
                (
                    "email_address",
                    models.CharField(
                        blank=True, db_column="Email_address", max_length=100, null=True
                    ),
                ),
                ("age", models.IntegerField(blank=True, db_column="Age", null=True)),
            ],
            options={
                "db_table": "patients",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "paymentid",
                    models.IntegerField(
                        db_column="PaymentID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "orderid",
                    models.IntegerField(blank=True, db_column="OrderID", null=True),
                ),
                (
                    "amount",
                    models.DecimalField(
                        db_column="Amount", decimal_places=2, max_digits=10
                    ),
                ),
                (
                    "paymentmethod",
                    models.CharField(db_column="PaymentMethod", max_length=50),
                ),
                ("paymentdate", models.DateField(db_column="PaymentDate")),
            ],
            options={
                "db_table": "payment",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Pharmacists",
            fields=[
                (
                    "pharmacistid",
                    models.IntegerField(
                        db_column="PharmacistID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "pharmacists_name_fname",
                    models.CharField(
                        blank=True,
                        db_column="Pharmacists_Name_Fname",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "pharmacists_name_mname",
                    models.CharField(
                        blank=True,
                        db_column="Pharmacists_Name_Mname",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "pharmacists_name_lname",
                    models.CharField(
                        blank=True,
                        db_column="Pharmacists_Name_Lname",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "contactnumber_type",
                    models.CharField(
                        blank=True,
                        db_column="ContactNumber_type",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "contactnumber_number",
                    models.BigIntegerField(
                        blank=True,
                        db_column="ContactNumber_number",
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "email_address",
                    models.CharField(
                        blank=True, db_column="Email_Address", max_length=255, null=True
                    ),
                ),
                (
                    "email_type",
                    models.CharField(
                        blank=True, db_column="Email_Type", max_length=255, null=True
                    ),
                ),
                (
                    "qualification_yearofgraduation",
                    models.IntegerField(
                        blank=True,
                        db_column="Qualification_yearOfGraduation",
                        null=True,
                    ),
                ),
                (
                    "qualification_fieldofstudy",
                    models.CharField(
                        blank=True,
                        db_column="Qualification_FieldOfStudy",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "pharmacists",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Policyprovider",
            fields=[
                (
                    "policyproviderid",
                    models.IntegerField(
                        db_column="PolicyProviderID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "policyprovider_name_fname",
                    models.CharField(
                        db_column="PolicyProvider_Name_Fname", max_length=255
                    ),
                ),
                (
                    "policyprovider_name_mname",
                    models.CharField(
                        blank=True,
                        db_column="PolicyProvider_Name_Mname",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "policyprovider_name_lname",
                    models.CharField(
                        db_column="PolicyProvider_Name_Lname", max_length=255
                    ),
                ),
                ("contactnumber", models.BigIntegerField(db_column="ContactNumber")),
                (
                    "email",
                    models.CharField(db_column="Email", max_length=255, unique=True),
                ),
                ("address", models.CharField(db_column="Address", max_length=255)),
            ],
            options={
                "db_table": "policyprovider",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "prescriptionid",
                    models.IntegerField(
                        db_column="PrescriptionID", primary_key=True, serialize=False
                    ),
                ),
                ("dosage", models.IntegerField(db_column="Dosage")),
                ("duration_days", models.IntegerField(db_column="Duration_Days")),
                ("startdate", models.DateField(db_column="StartDate")),
                ("enddate", models.DateField(db_column="EndDate")),
                ("date", models.DateField(db_column="Date")),
                ("datewritten", models.DateField(db_column="DateWritten")),
            ],
            options={
                "db_table": "prescription",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PresMedicine",
            fields=[
                (
                    "pmid",
                    models.IntegerField(
                        db_column="PMID", primary_key=True, serialize=False
                    ),
                ),
            ],
            options={
                "db_table": "pres_medicine",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stockid", models.IntegerField(db_column="StockID")),
                (
                    "quantity",
                    models.IntegerField(blank=True, db_column="Quantity", null=True),
                ),
                (
                    "threshold",
                    models.IntegerField(blank=True, db_column="Threshold", null=True),
                ),
            ],
            options={
                "db_table": "stock",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Suppliers",
            fields=[
                (
                    "supplierid",
                    models.IntegerField(
                        db_column="SupplierID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "supplier_name_fname",
                    models.CharField(db_column="Supplier_Name_Fname", max_length=50),
                ),
                (
                    "supplier_name_mname",
                    models.CharField(db_column="Supplier_Name_Mname", max_length=50),
                ),
                (
                    "supplier_name_lname",
                    models.CharField(db_column="Supplier_Name_Lname", max_length=50),
                ),
                (
                    "contactnumber_type",
                    models.CharField(db_column="ContactNumber_type", max_length=20),
                ),
                (
                    "contactnumber_number",
                    models.BigIntegerField(
                        blank=True,
                        db_column="ContactNumber_number",
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "email_address",
                    models.CharField(
                        db_column="Email_Address", max_length=50, unique=True
                    ),
                ),
                ("email_type", models.CharField(db_column="Email_Type", max_length=20)),
                ("address", models.CharField(db_column="Address", max_length=100)),
                (
                    "address_type",
                    models.CharField(db_column="Address_Type", max_length=20),
                ),
            ],
            options={
                "db_table": "suppliers",
                "managed": False,
            },
        ),
    ]
